from utils.i18n import t

def get_display_columns():
    return {
        "Ticker": t("col_ticker"),
        "Intermediario": t("col_broker"),
        "Nome": t("col_name"),
        "Tipo": t("col_type"),
        "Area": t("col_area"),
        "Settore": t("col_sector"),
        "Emittente": t("col_issuer"),
        "Valuta": t("col_currency"),
        "Quantita": t("col_quantity"),
        "Prezzo Attuale": t("col_price_current"),
        "Valore": t("col_value"),
        "Dividendi Netti Incassati": t("col_dividends"),
        "Costo Medio Stimato": t("col_avg_cost"),
        "Costo Totale Stimato": t("col_total_cost"),
        "P/L": t("col_pl"),
        "P/L %": t("col_pl_pct"),
        "P/L Netto Stimato": t("col_pl_net"),
        "P/L Giornaliero": t("col_pl_daily"),
        "P/L Giornaliero %": t("col_pl_daily_pct"),
        
        # ✅ AGGIUNTA per operations preview
        "Data": t("col_date"),
        "Prezzo": t("col_trade_price"),
        "AvgCostBefore": t("col_avg_cost_before"),
        "RealizedTradePL": t("col_realized_trade_pl"),
        "ID": t("col_id"),
        "SpeseEuro": t("col_fees_eur"),
        "Tassa": t("col_tax"),
        "Cambio": t("col_fx"),
        "FlussoNetto": t("col_cashflow"),
        "Prezzo medio s/carico": t("col_avg_cost_trade"),
        "PositionKey": t("col_position_key"),
        "_rowid": t("col_rowid"),
        "AvgCostAfter": t("col_avg_cost_after"),
        "QtyOpenAfter": t("col_qty_open_after"),
        "CostOpenAfter": t("col_cost_open_after"),
        "CashflowCalc": t("col_cashflow_calc"),
        "TaxEuroCalc": t("col_tax_calc"),
        # XIRR / flows
        "Operazioni": t("col_flow_operations"),
        "Dividendi": t("col_flow_dividends"),
        "Valore finale": t("col_flow_final_value"),
        "Totale": t("col_flow_total"),
    }
