[theme]
# base = "dark"

primaryColor = "#00C896"        # verde elegante
backgroundColor = "#0e1117"     # sfondo principale (nero/blu)
secondaryBackgroundColor = "#262730"  # pannelli/grigio scuro
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
